trilobit:
    cookiebar:
        position:
            top:
            bottom:
            top-left:
            top-right:
            bottom-left:
            bottom-right:

        theme:
            block:
            edgeless:
            classic:

        palette:
            css:
            custom:
            theme1:
                popup:
                    background: '#000'
                button:
                    background: '#f1d600'

            theme2:
                popup:
                    background: '#eaf7f7'
                    text: '#5c7291'
                button:
                    background: '#56cbdb'
                    text: '#fff'

            theme3:
                popup:
                    background: '#252e39'
                button:
                    background: '#14a7d0'

            theme4:
                popup:
                    background: '#000'
                    text: '#0f0'
                button:
                    background: '#0f0'

            theme5:
                popup:
                    background: '#3937a3'
                button:
                    background: '#e62576'

            theme6:
                popup:
                    background: '#64386b'
                    text: '#ffcdfd'
                button:
                    background: '#f8a8ff'
                    text: '#3f0045'

            theme7:
                popup:
                    background: '#237afc'
                button:
                    background: '#fff'

            theme8:
                popup:
                    background: '#a00'
                    text: '#fdd'
                button:
                    background: '#f00'

            theme9:
                popup:
                    background: '#383b75'
                button:
                    background: '#f1d600'

            theme10:
                popup:
                    background: '#1d8a8a'
                button:
                    background: '#62ffaa'

            theme11:
                popup:
                    background: '#edeff5'
                    text: '#838391'
                button:
                    background: '#4b81e8'

            theme12:
                popup:
                    background: '#343c66'
                    text: '#cfcfe8'
                button:
                    background: '#f71559'

            theme13:
                popup:
                    background: '#216942'
                    text: '#b2d192'
                button:
                    background: '#afed71'

            theme14:
                popup:
                    background: '#3c404d'
                    text: '#d6d6d6'
                button:
                    background: '#8bed4f'

            theme15:
                popup:
                    background: '#eb6c44'
                    text: '#fff'
                button:
                    background: '#f5d948'

            theme16:
                popup:
                    background: '#efefef'
                    text: '#404040'
                button:
                    background: '#8ec760'
                    text: '#fff'
